### PR TITLE
Fix item socket to make sure users are able to create Medicine items

### LINKED ISSUE #385: Fix item socket to make sure users are able to create Medicine items
## Description of the problem
Users have no way of properly creating new medicine items right now, as selecting medicine will not have it go in the medicine pocket of the bag (it seemingly goes nowhere).
## Current behavior
- When adding new items like "Potions" and setting them to Medicine socket to retrieve them in the right socket in game, they are not displayed in the bag.
- Healing items that are provided by PSDK work fine as they seem to go in the medicine pocket as expected HOWEVER when you look at them on Studio it displays `Treasures` instead.
- If you click on the data tab, it will show "Medicine" instead of "Treasures", but "Treasures" is not available in the drop down (see tje [preview](https://imgur.com/BvopqKI)).
- Correcting this from treasures -> medicine will make the item not go in your medicine bag.
- For now, Studio is setting the socket value to 0 and not 6.
## Excepted behavior
- When adding new items like "Potions" and setting them to Medicine socket, I would like to see them in my Medicine bag socket in game.
- On Studio, the data tab should display "Medicine" and not "Treasures".
- For Medicine items, Studio should set the socket value to 6 and not 0.

### PR DESCRIPTION
**Pull request by Palbolsky**
## Description

This PR fixes an issue with the Medicine socket.
- The socket display on the items page has been fixed ;
- The socket selection has also been fixed.

Closes #385

## Tests to perform

- [x] The user can put an item in the Medicine socket
- [x] The user can put an item in any socket (and this corresponds to PSDK)

### CODE REVIEW

File: src/utils/ReadingProjectText.ts [hunk 1]
```diff
@@ -254,14 +254,14 @@ export const getItemPocketText = (item: StudioItem, state: State): string => {
       defaultLanguage: state.projectConfig.language_config.defaultLanguage,
     },
     ITEM_POCKET_NAME_TEXT_ID,
-    pocketMapping[item.socket] || item.socket
+    pocketMapping[item.socket] ?? item.socket
```
Comment (NuriYuri) [inline src/utils/ReadingProjectText.ts:257]: Classique :p

**Review by NuriYuri — APPROVED** [review]

**Review by AerunDev — APPROVED** [review]
Testé et c'est nickel, bien joué ! 😄
