### PR TITLE
Fix quests custom goals text being set to the same ID when created by importing existing data

### LINKED ISSUE #680: Creating quests by importing another one with custom goals make those goals using the same text entry
## Describe the bug
Creating new quests by importing existing one with custom goals makes the two goals sharing the same text entry. So editing one of them will edit the second one.

## Steps to reproduce
1. Go to Quests database UI
2. Add a custom goal on a quest and note the details
3. Click on "+ New quest"
4. Fill the form and use the "Other data" category to import a quest with a custom goal named "Custom goal test"
5. Edit one of them into "Custom goal test 2"
6. Check the other one
7. See error

## Expected behavior
Custom goals should have their own text entry.

## Relevant logs and/or screenshots
[See the link of the Discord support topic](https://discord.com/channels/143824995867557888/1433155165447389316/1433155165447389316)

## Which version of Pokémon Studio are you using?
2.7.0

### PR DESCRIPTION
**Pull request by Aelysya**
## Description

This PR fixes two issues that are closely related. When custom goals are created via an importation method (whether by creating an entire quest with existing data, or only importing another quest's goals) the text IDs used by these goals were the same as the imported ones, creating conflicts.

closes #680 

## Note before testing

- [x] Have an existing quest in your database with one or more custom goals set.

## Tests to perform

- [x] Create a new quest using the "Other data" method, the copied custom goals have newly assigned IDs and the texts have been copied
- [x] In an existing quest, import goals from another quest, the copied custom goals have newly assigned IDs and the texts have been copied

### CODE REVIEW

File: src/views/components/database/quest/editors/QuestNewEditor.tsx [hunk 1]
```diff
@@ -64,7 +71,20 @@ export const QuestNewEditor = forwardRef<EditorHandlingClose, QuestNewEditorProp
     let newQuest = createQuest(quests, categoryRef.current === 'primary', 'default');
 
     if (importing && selectedQuest !== '__undef__') {
-      newQuest = importQuestData(newQuest, quests[selectedQuest]);
+      newQuest = importQuestData(newQuest, quests[selectedQuest], quests);
+
+      // Copy custom objectives texts
```
Comment (Palbolsky) [inline src/views/components/database/quest/editors/QuestNewEditor.tsx:76]: Petite duplication de code sur la copie des textes des objectifs personnalisés (code également présent dans le composant QuestGoalImportEditor). Il n'y a pas moyen de créer une fonction ?

**Review by Palbolsky — APPROVED** [review]
Testé et le bug est bien corrigé.
J'ai simplement relevé une duplication de code, à voir si on peut créer facilement une fonction.

File: src/views/components/database/quest/editors/QuestNewEditor.tsx (hunk 1 above)
Comment (Aelysya) [reply src/views/components/database/quest/editors/QuestNewEditor.tsx:76]: Oui probablement, je regarderai pour opti ça

**Review by Palbolsky — APPROVED** [review]

**Review by AerunDev — APPROVED** [review]
