### PR TITLE
Fix dialog overlay softlock with multiple clicks

### LINKED ISSUE #724: Fix possible softlock if the user click multiple times on a data block of the database
## Describe the bug
When you're opening and closing the editor of a data block, Studio can be soft locked and still displaying the editor overlay even if the editor is closed.

## Steps to reproduce
1. Go to the Items page
2. Click on the first data block multiple times to open and close it successively
3. See the soft lock

## Expected behavior
The editor overlay should not be displayed if the editor is closed.

## Relevant logs and/or screenshots

Image

## Which version of Pokémon Studio are you using?
2.9.0

### PR DESCRIPTION
**Pull request by Xpiance**
Fix a race condition in EditorOverlayV2 where multiple rapid clicks could leave the overlay visible after the dialog was already closed.

The change makes sure older delayed open actions do not run after a newer open or close action.

## Template ##

Thank you for your contribution to the **Pokémon Studio** repo.

Before submitting this PR into the develop branch, please make sure:

- [x] Your code builds clean without any errors or warnings
- [x] You are following the [Code guidelines](../CodeGuidelines.md)
- [x] You tested your code to make sure it does what it is supposed to do

## Description

When you're opening and closing the editor of a data block, Studio can be soft locked and still displaying the editor overlay even if the editor is closed. This should not happen.

This change invalidates previous dialog actions, cancels pending delayed opens, and only applies close cleanup if it still belongs to the latest action.

## Note before testing

I also checked the other database editor pages and could not reproduce the issue there.

## Tests to perform

From original issue:
1. Go to the Items page
2. Click on the first data block multiple times to open and close it successively
3. See the soft lock (Verify that the softlock no longer happens)

Closes https://github.com/PokemonWorkshop/PokemonStudio/issues/724

### CODE REVIEW

**Review by AerunDev — APPROVED** [review]
Hello @Xpiance!
Thank you so much for this contribution.
I've just tested your fix and this is fully functional to me. I'll let a code contributor approve the changes and we'll be able to merge it for the next release.

File: src/views/components/editor/EditorOverlayV2.tsx [hunk 1]
```diff
@@ -185,11 +185,31 @@ export const defineEditorOverlay = <Keys extends string, Props extends Record<st
...
+      const currentAction = prepareDialogAction();
       handleCloseRef.current?.onClose();
-      if (dialogRef.current && backdropRef.current)
-        closeDialogWithAnimation(dialogRef.current, backdropRef.current, isCenter, () => setCurrentDialog(undefined));
+      if (dialogRef.current && backdropRef.current) {
+        closeDialogWithAnimation(dialogRef.current, backdropRef.current, isCenter, () => {
+          if (currentAction !== dialogActionRef.current) return;
+          setCurrentDialog(undefined);
+        });
+      } else {
```
Comment (Menthx) [inline src/views/components/editor/EditorOverlayV2.tsx]: Use else if here

**Review by Menthx — APPROVED** [review]
Just a little change before merge, Thanks for contributing !

File: src/views/components/editor/EditorOverlayV2.tsx (hunk 1 above)
Comment (Xpiance) [reply src/views/components/editor/EditorOverlayV2.tsx]: Should be changed now! Thanks 😃

**Review by Menthx — APPROVED** [review]
